/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as FaviconRouteImport } from './routes/favicon'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AppInboxRouteRouteImport } from './routes/_app/inbox/route'
import { Route as ApiFaviconRouteImport } from './routes/api/favicon'
import { Route as AppInboxIndexRouteImport } from './routes/_app/inbox/index'
import { Route as AppInboxArticleRouteImport } from './routes/_app/inbox/$article'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconRoute = FaviconRouteImport.update({
  id: '/favicon',
  path: '/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxRouteRoute = AppInboxRouteRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiFaviconRoute = ApiFaviconRouteImport.update({
  id: '/api/favicon',
  path: '/api/favicon',
  getParentRoute: () => rootRouteImport,
} as any)
const AppInboxIndexRoute = AppInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppInboxRouteRoute,
} as any)
const AppInboxArticleRoute = AppInboxArticleRouteImport.update({
  id: '/$article',
  path: '/$article',
  getParentRoute: () => AppInboxRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favicon': typeof FaviconRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/inbox': typeof AppInboxRouteRouteWithChildren
  '/api/favicon': typeof ApiFaviconRoute
  '/inbox/$article': typeof AppInboxArticleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/inbox/': typeof AppInboxIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favicon': typeof FaviconRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/api/favicon': typeof ApiFaviconRoute
  '/inbox/$article': typeof AppInboxArticleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/inbox': typeof AppInboxIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/favicon': typeof FaviconRoute
  '/mcp': typeof McpRoute
  '/register': typeof RegisterRoute
  '/_app/inbox': typeof AppInboxRouteRouteWithChildren
  '/api/favicon': typeof ApiFaviconRoute
  '/_app/inbox/$article': typeof AppInboxArticleRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/inbox/': typeof AppInboxIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favicon'
    | '/mcp'
    | '/register'
    | '/inbox'
    | '/api/favicon'
    | '/inbox/$article'
    | '/api/auth/$'
    | '/inbox/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favicon'
    | '/mcp'
    | '/register'
    | '/api/favicon'
    | '/inbox/$article'
    | '/api/auth/$'
    | '/inbox'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/favicon'
    | '/mcp'
    | '/register'
    | '/_app/inbox'
    | '/api/favicon'
    | '/_app/inbox/$article'
    | '/api/auth/$'
    | '/_app/inbox/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  FaviconRoute: typeof FaviconRoute
  McpRoute: typeof McpRoute
  RegisterRoute: typeof RegisterRoute
  ApiFaviconRoute: typeof ApiFaviconRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon': {
      id: '/favicon'
      path: '/favicon'
      fullPath: '/favicon'
      preLoaderRoute: typeof FaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/favicon': {
      id: '/api/favicon'
      path: '/api/favicon'
      fullPath: '/api/favicon'
      preLoaderRoute: typeof ApiFaviconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/inbox/': {
      id: '/_app/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AppInboxIndexRouteImport
      parentRoute: typeof AppInboxRouteRoute
    }
    '/_app/inbox/$article': {
      id: '/_app/inbox/$article'
      path: '/$article'
      fullPath: '/inbox/$article'
      preLoaderRoute: typeof AppInboxArticleRouteImport
      parentRoute: typeof AppInboxRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppInboxRouteRouteChildren {
  AppInboxArticleRoute: typeof AppInboxArticleRoute
  AppInboxIndexRoute: typeof AppInboxIndexRoute
}

const AppInboxRouteRouteChildren: AppInboxRouteRouteChildren = {
  AppInboxArticleRoute: AppInboxArticleRoute,
  AppInboxIndexRoute: AppInboxIndexRoute,
}

const AppInboxRouteRouteWithChildren = AppInboxRouteRoute._addFileChildren(
  AppInboxRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppInboxRouteRoute: typeof AppInboxRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppInboxRouteRoute: AppInboxRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  FaviconRoute: FaviconRoute,
  McpRoute: McpRoute,
  RegisterRoute: RegisterRoute,
  ApiFaviconRoute: ApiFaviconRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
