export const CATEGORY_CLASSIFIER_PROVENANCE = "classifier";
export const GENERAL_CATEGORY_LABEL = "General";

export type CategoryTaxonomyEntry = {
  label: string;
  slug: string;
  keywords: readonly string[];
  domainHints: readonly string[];
};

export const MIXED_FEED_HOSTS = new Set([
  "news.ycombinator.com",
  "lobste.rs",
  "reddit.com",
  "old.reddit.com",
  "slashdot.org",
]);

export const CATEGORY_TAXONOMY: readonly CategoryTaxonomyEntry[] = [
  {
    label: "Software Engineering",
    slug: "software-engineering",
    keywords: [
      "api",
      "architecture",
      "backend",
      "code",
      "compiler",
      "database",
      "developer",
      "engineering",
      "frontend",
      "github",
      "infrastructure",
      "javascript",
      "kubernetes",
      "programming",
      "python",
      "react",
      "rust",
      "software",
      "typescript",
    ],
    domainHints: ["github.com", "gitlab.com", "stackoverflow.com", "medium.com"],
  },
  {
    label: "Technology",
    slug: "technology",
    keywords: [
      "ai",
      "app",
      "chip",
      "computer",
      "gadget",
      "hardware",
      "internet",
      "platform",
      "startup",
      "tech",
      "technology",
      "web",
    ],
    domainHints: ["techcrunch.com", "wired.com", "theverge.com", "arstechnica.com"],
  },
  {
    label: "Security",
    slug: "security",
    keywords: [
      "attack",
      "breach",
      "cve",
      "exploit",
      "malware",
      "password",
      "privilege",
      "ransomware",
      "security",
      "threat",
      "vulnerability",
    ],
    domainHints: ["krebsonsecurity.com", "bleepingcomputer.com", "hackercombat.com"],
  },
  {
    label: "AI",
    slug: "ai",
    keywords: [
      "agent",
      "artificial intelligence",
      "embedding",
      "language model",
      "llm",
      "machine learning",
      "model",
      "neural",
      "openai",
      "transformer",
    ],
    domainHints: ["openai.com", "huggingface.co", "arxiv.org"],
  },
  {
    label: "Science",
    slug: "science",
    keywords: [
      "astronomy",
      "biology",
      "brain",
      "climate",
      "discovery",
      "experiment",
      "migration",
      "physics",
      "research",
      "science",
      "scientist",
      "space",
    ],
    domainHints: ["nature.com", "science.org", "news.exeter.ac.uk", "engineering.columbia.edu"],
  },
  {
    label: "Business",
    slug: "business",
    keywords: [
      "business",
      "company",
      "earnings",
      "funding",
      "market",
      "revenue",
      "startup",
      "stock",
      "venture",
    ],
    domainHints: ["bloomberg.com", "wsj.com", "ft.com", "techcrunch.com"],
  },
  {
    label: "Finance",
    slug: "finance",
    keywords: [
      "bank",
      "bitcoin",
      "crypto",
      "economy",
      "finance",
      "inflation",
      "investment",
      "market",
      "money",
      "stock",
    ],
    domainHints: ["finance.yahoo.com", "marketwatch.com", "coinbase.com"],
  },
  {
    label: "Politics",
    slug: "politics",
    keywords: [
      "congress",
      "election",
      "government",
      "law",
      "policy",
      "politics",
      "president",
      "regulation",
      "senate",
      "supreme court",
    ],
    domainHints: ["politico.com", "whitehouse.gov", "congress.gov"],
  },
  {
    label: "Culture",
    slug: "culture",
    keywords: ["art", "book", "culture", "essay", "film", "history", "music", "society", "writing"],
    domainHints: ["newyorker.com", "theatlantic.com", "lithub.com"],
  },
  {
    label: "Design",
    slug: "design",
    keywords: [
      "brand",
      "design",
      "figma",
      "interface",
      "product design",
      "typography",
      "ui",
      "user experience",
      "ux",
      "visual",
    ],
    domainHints: ["dribbble.com", "figma.com", "smashingmagazine.com"],
  },
  {
    label: "Health",
    slug: "health",
    keywords: [
      "clinical",
      "doctor",
      "drug",
      "health",
      "medical",
      "medicine",
      "patient",
      "public health",
      "vaccine",
    ],
    domainHints: ["nih.gov", "who.int", "nejm.org"],
  },
  {
    label: "Sports",
    slug: "sports",
    keywords: [
      "baseball",
      "basketball",
      "football",
      "game",
      "league",
      "match",
      "soccer",
      "sports",
      "team",
    ],
    domainHints: ["espn.com", "theathletic.com", "mlb.com", "nba.com", "nfl.com"],
  },
  {
    label: "Travel",
    slug: "travel",
    keywords: [
      "airline",
      "city guide",
      "flight",
      "hotel",
      "restaurant",
      "tourism",
      "travel",
      "trip",
    ],
    domainHints: ["lonelyplanet.com", "cntraveler.com"],
  },
  {
    label: "Food",
    slug: "food",
    keywords: ["baking", "chef", "cooking", "food", "kitchen", "recipe", "restaurant"],
    domainHints: ["seriouseats.com", "bonappetit.com"],
  },
  {
    label: "News",
    slug: "news",
    keywords: ["breaking", "daily", "headline", "latest", "news", "report", "world"],
    domainHints: ["apnews.com", "reuters.com", "bbc.com", "nytimes.com"],
  },
];
