export {
  FEED_REFRESH_JOBS_STREAM_KEY,
  JOBS_CONSUMER_GROUP,
  JOBS_DEAD_LETTER_STREAM_KEY,
  JOBS_STREAM_KEY,
  OPML_JOBS_STREAM_KEY,
  consumeJobs,
  ensureConsumerGroup,
  fieldsForJob,
  getStreamKeyForJobType,
  normalizeQueueOptions,
  parseJob,
  parseJobMessageFields,
  toRedisStreamFieldList,
  type ConsumeJobsOptions,
  type FeedRefreshJob,
  type Job,
  type JobMessage,
  type JobType,
  type OpmlImportFeedJob,
  type OpmlImportJob,
  type QueueOptions,
} from "./services/queue/job";

export {
  createHostRateLimiter,
  createMemoryHostRateLimitStore,
  createRedisHostRateLimitStore,
  runFeedRefresh,
  discoverFeedUrlFromHtml,
  parseFeedDocument,
  shouldEnrichInsertedItems,
  CATEGORY_CLASSIFIER_PROVENANCE,
  MISCELLANEOUS_CATEGORY_LABEL,
  classifyFeedCategories,
  classifyFeedItemCategories,
  isMixedFeedHost,
  MAX_CLASSIFIER_LABELS,
  shouldSuppressClassifierFeedFallback,
  canonicalWinsOnConflictSql,
  syncInferredFeedCategories,
  classifyFeedCategoriesByEmbedding,
  classifyFeedItemCategoriesByEmbedding,
  embedTexts,
  resetCategoryPrototypeCacheForTests,
  CLASSIFIER_TAXONOMY_VERSION,
  EMBEDDING_CLASSIFIER_METHOD,
  KEYWORD_CLASSIFIER_METHOD,
  KEYWORD_CLASSIFIER_MODEL_ID,
  type CategoryClassification,
  type ClassifierModelInfo,
  type EmbeddingClassifierConfig,
  type FeedCategoryClassificationInput,
  type FeedItemCategoryClassificationInput,
  type FeedIngestDatabase,
  type FeedRefreshCategoryStats,
  type FeedRefreshResult,
  type HostRateLimiter,
  type HtmlFeedFailureClass,
  type InferredCategoryLabel,
  type SearchSyncConfig,
} from "./services/feed";

export { buildArticleIdentity, normalizeArticleUrl } from "./lib/article-identity";
export { decodeHtmlEntities } from "./lib/html-entities";
