import { afterEach, beforeEach, describe, expect, mock, test } from "bun:test";
import { createArticleClip } from "@modules/articles/write/clips/operations";

const originalFetch = globalThis.fetch;

function pendingClipRow(overrides: Record<string, unknown> = {}) {
  return {
    id: "clip_1",
    userId: "user_1",
    url: "https://example.com/article",
    title: "example.com",
    content: null,
    contentHtml: null,
    contentText: null,
    contentMarkdown: null,
    contentStatus: "pending",
    contentSource: "link_only",
    extractionErrorCode: null,
    extractionErrorMessage: null,
    extractedContentHtml: null,
    extractedContentText: null,
    extractedContentStatus: "pending",
    extractedContentError: null,
    extractedContentUpdatedAt: null,
    note: null,
    isRead: false,
    isSaved: true,
    createdAt: new Date("2026-04-08T10:00:00.000Z"),
    updatedAt: new Date("2026-04-08T10:00:00.000Z"),
    ...overrides,
  };
}

describe("createArticleClip", () => {
  beforeEach(() => {
    globalThis.fetch = mock(async () => {
      throw new Error("fetch must not be called from the request path");
    }) as unknown as typeof fetch;
  });

  afterEach(() => {
    globalThis.fetch = originalFetch;
  });

  test("persists a pending link-only clip and queues extraction without fetching", async () => {
    const returning = mock(() => Promise.resolve([pendingClipRow()]));
    const values = mock(() => ({ returning }));
    const insert = mock(() => ({ values }));
    const fakeDb = { insert } as unknown as Parameters<typeof createArticleClip>[0];
    const enqueueExtractionJob = mock(() => Promise.resolve("stream-id-1"));

    const result = await createArticleClip(
      fakeDb,
      "user_1",
      { url: "https://example.com/article" },
      { enqueueExtractionJob },
    );

    expect(result.contentStatus).toBe("pending");
    expect(result.contentHtml).toBeNull();
    expect(globalThis.fetch).not.toHaveBeenCalled();
    expect(enqueueExtractionJob).toHaveBeenCalledTimes(1);
    const job = enqueueExtractionJob.mock.calls[0]![0];
    expect(job).toMatchObject({
      type: "article.extract",
      payload: {
        articleId: "clip_1",
        userId: "user_1",
        reason: "clip_created",
        replaceClipTitle: true,
        autogeneratedTitleAtQueue: "example.com",
      },
    });
  });

  test("does not enqueue extraction when explicit content is provided", async () => {
    const returning = mock(() =>
      Promise.resolve([
        pendingClipRow({
          title: "My title",
          content: "Explicit content",
          contentText: "Explicit content",
          contentStatus: "partial",
          contentSource: "text_fallback",
        }),
      ]),
    );
    const values = mock(() => ({ returning }));
    const insert = mock(() => ({ values }));
    const fakeDb = { insert } as unknown as Parameters<typeof createArticleClip>[0];
    const enqueueExtractionJob = mock(() => Promise.resolve("stream-id-1"));

    const result = await createArticleClip(
      fakeDb,
      "user_1",
      { url: "https://example.com/article", title: "My title", content: "Explicit content" },
      { enqueueExtractionJob },
    );

    expect(result.contentText).toBe("Explicit content");
    expect(enqueueExtractionJob).not.toHaveBeenCalled();
  });

  test("marks replaceClipTitle false when the user supplied an explicit title", async () => {
    const returning = mock(() => Promise.resolve([pendingClipRow({ title: "User title" })]));
    const values = mock(() => ({ returning }));
    const insert = mock(() => ({ values }));
    const fakeDb = { insert } as unknown as Parameters<typeof createArticleClip>[0];
    const enqueueExtractionJob = mock(() => Promise.resolve("stream-id-1"));

    await createArticleClip(
      fakeDb,
      "user_1",
      { url: "https://example.com/article", title: "User title" },
      { enqueueExtractionJob },
    );

    const job = enqueueExtractionJob.mock.calls[0]![0];
    expect(job.payload.replaceClipTitle).toBe(false);
    expect(job.payload.autogeneratedTitleAtQueue).toBeUndefined();
  });

  test("queue publication failure leaves the clip committed with a failed extracted state and still returns 201 detail", async () => {
    const returning = mock(() => Promise.resolve([pendingClipRow()]));
    const values = mock(() => ({ returning }));
    const insert = mock(() => ({ values }));
    const updateWhere = mock(() => Promise.resolve());
    const updateSet = mock(() => ({ where: updateWhere }));
    const update = mock(() => ({ set: updateSet }));
    const fakeDb = { insert, update } as unknown as Parameters<typeof createArticleClip>[0];
    const enqueueExtractionJob = mock(() => Promise.reject(new Error("redis unavailable")));

    const result = await createArticleClip(
      fakeDb,
      "user_1",
      { url: "https://example.com/article" },
      { enqueueExtractionJob },
    );

    expect(result.id).toBe("clip_1");
    expect(update).toHaveBeenCalledTimes(1);
    expect(updateSet).toHaveBeenCalledWith(
      expect.objectContaining({ extractedContentStatus: "failed" }),
    );
  });

  test("rejects explicit content over the 1 MiB field budget without touching the database", async () => {
    const insert = mock(() => ({ values: mock() }));
    const fakeDb = { insert } as unknown as Parameters<typeof createArticleClip>[0];

    await expect(
      createArticleClip(fakeDb, "user_1", {
        url: "https://example.com/article",
        content: "a".repeat(1024 * 1024 + 1),
      }),
    ).rejects.toMatchObject({
      status: 413,
      code: "ARTICLE_CONTENT_TOO_LARGE",
    });
    expect(insert).not.toHaveBeenCalled();
  });

  test("accepts explicit content at exactly the 1 MiB field budget", async () => {
    const returning = mock(() =>
      Promise.resolve([
        {
          id: "clip_1",
          userId: "user_1",
          url: "https://example.com/article",
          title: "My title",
          content: "a".repeat(1024 * 1024),
          contentHtml: null,
          contentText: "a".repeat(1024 * 1024),
          contentMarkdown: null,
          contentStatus: "partial",
          contentSource: "text_fallback",
          extractionErrorCode: null,
          extractionErrorMessage: null,
          note: null,
          isRead: false,
          isSaved: true,
          createdAt: new Date("2026-04-08T10:00:00.000Z"),
          updatedAt: new Date("2026-04-08T10:00:00.000Z"),
        },
      ]),
    );
    const values = mock(() => ({ returning }));
    const insert = mock(() => ({ values }));
    const fakeDb = { insert } as unknown as Parameters<typeof createArticleClip>[0];

    await expect(
      createArticleClip(fakeDb, "user_1", {
        url: "https://example.com/article",
        title: "My title",
        content: "a".repeat(1024 * 1024),
      }),
    ).resolves.toMatchObject({ title: "My title" });
  });
});
